### ISSUE TITLE
I cant undertand how to check for specific blocks in chunk

### ISSUE THREAD

**Issue by Kotkov-Vasili** [MestreLion/mcworldlib#1]
Hello.Thanks for lib,by the way i cant undertand how its works,i am new at python,so can you please give example of code for checking for specific block inside chunk,please? My minecraft version is 1.12.2,if its  important.

**Comment by MestreLion** [comment]
I just pushed a few commits that add block-reading capabilities to MCWorldLib. Now it's really easy to get all info about a block in a given position:

```python
import mcworldlib as mc
world = mc.load('New World')
block = world.get_block_at((100, 63, 100))
print(block)
```

And the result:

```
INFO  : Loading World 'New World': /home/rodrigo/.minecraft/saves/New World
DEBUG : Loading Region (0, 0): /home/rodrigo/.minecraft/saves/New World/region/r.0.0.mca
{Name: "minecraft:diamond_block"}
```
