### ISSUE TITLE
Regions aren't properly loaded when loading Beta 1.7.3 world

### ISSUE THREAD

**Issue by Fhoughton** [MestreLion/mcworldlib#13]
When attempting to load a beta 1.7.3 world it is processed correctly without errors but the regions aren't loaded

```python
import mcworldlib as mc

world = mc.load("<ABSOLUTE PATH>\Beta Test World 1.7.3")

mc.pretty(world.level) # Outputs fine

mc.pretty(world.regions) 

# Output:
#{   <Dimension.THE_END: 1>: <Regions(0 regions)>,
#    <Dimension.THE_NETHER: -1>: <Regions(0 regions)>,
#   <Dimension.OVERWORLD: 0>: <Regions(0 regions)>}
```

Inside the region folder of the world there are 3 mcr region files (```r.0.0.mcr```, ```r.0.-1.mcr``` and ```r.-1.-1.mcr```)

Loading the region directly with ```r = mc.load_region("./region/r.0.0.mcr")``` works but attempting to process the chunks of the region results in an error:
```python
r = mc.load_region("./region/r.0.0.mcr")
list(list(r.chunks)[0].get_blocks())
````

Produces:
```
Traceback (most recent call last):
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcworldlib\chunk.py", line 54, in get_blocks
    for section in self.data_root['Sections']:
                   ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\<USER>\AppData\Local\Programs\Python\Python311\Lib\site-packages\nbtlib\tag.py", line 1167, in __getitem__
    return super().__getitem__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Sections'
```

**Comment by MestreLion** [comment]
By "Beta 1.7.3" you mean a version around October-November 2013, [The Update that Changed the World](https://minecraft.fandom.com/wiki/The_Update_that_Changed_the_World)? 

Block and Chunk structure in the NBT data changed _substantially_ in, IIRC, Minecraft 1.13 from 2017. And that broke basically all tools from that era, such as MCEdit and its [`pymclevel`](https://github.com/mcedit/pymclevel) library. This incompatibility was my main motivation to create _this_ library, so it would be able to properly decode MC 1.13 Chunks and Blocks when no other tool could.

As such, I didn't bother to add compatibility with MC versions _prior_ to that. There are many, many tools for that already. You can also try my previous project [`pymctoolslib`](https://github.com/MestreLion/pymctoolslib)

**Comment by Fhoughton** [comment]
> By "Beta 1.7.3" you mean a version around October-November 2013, [The Update that Changed the World](https://minecraft.fandom.com/wiki/The_Update_that_Changed_the_World)?
> 
> Block and Chunk structure in the NBT data changed _substantially_ in, IIRC, Minecraft 1.13 from 2017. And that broke basically all tools from that era, such as MCEdit and its [`pymclevel`](https://github.com/mcedit/pymclevel) library. This incompatibility was my main motivation to create _this_ library, so it would be able to properly decode MC 1.13 Chunks and Blocks when no other tool could.
> 
> As such, I didn't bother to add compatibility with MC versions _prior_ to that. There are many, many tools for that already. You can also try my previous project [`pymctoolslib`](https://github.com/MestreLion/pymctoolslib)

Sorry for the late reply, no I was referring to this version https://minecraft.fandom.com/wiki/Java_Edition_Beta_1.7.3 which released in 2011. That's outside the supported range you suggested still though of course so I'm happy to close the issue for now.

**Comment by MestreLion** [comment]
Oh, _that_ Beta. Yeah, that's _ancient_. It predates named ID's (from MC 1.11 IIRC), and I believe it also has a different file naming scheme (mcr/mca), when name changed from "region file" to "anvil file" or vice-versa.

The raw chunk NBT data itself might be readable, but surely any semantics applied will be incorrect. I think Amulet can read Beta files, it was in their project scope to be fully backward-compatible with all MC versions. If not, `pymclevel` might, as it is a very old project.
