### ISSUE TITLE
world.get_block_at((x, y, z)) always returns None

### ISSUE THREAD

**Issue by fqhd** [MestreLion/mcworldlib#19]
I'm using minecraft version 1.21.1 on manjaro linux. Here is the code I am testing with:

```js
    world = mc.load(world_path)
    block = world.get_block_at((0, 0, 0))
    print(block) # This always prints None
```

After placing a block at 0, 0, 0 and saving the world, the library fails to identify the correct block at that location.

**Comment by MestreLion** [comment]
Yes, this is known and already reported in #10 

It is supposedly fixed by #17 , but I don't have the time to test that PR
