### ISSUE TITLE
That i need to change to make it work with 1.12.2 worlds ?

### ISSUE THREAD

**Issue by Kotkov-Vasili** [MestreLion/mcworldlib#2]
Hello,thank for lib,but do you know that i need to change to make it work with 1.12.2 worlds?

**Comment by MestreLion** [comment]
You're welcome!

Unfortunately my lib only works with 1.13+ worlds. There was a crucial change in 1.13, called ["The Flattening"](https://minecraft.gamepedia.com/Java_Edition_1.13/Flattening) that was possibly the single biggest change in World and block format in all Minecraft history. It broke many tools what worked fine for more than a decade, such as [PyMCLevel](https://github.com/mcedit/pymclevel), which my lib was inspired by. 

It might be possible to adjust my library to work with pre-flattening worlds, but I believe a better solution is to use one of the many, many other libraries out there that _do_ work with(and _only_ with) pre-1.13.
