### ISSUE TITLE
Static OS

### ISSUE THREAD

**Issue by cullen6995** [MestreLion/mcworldlib#3]
Looks for ~/.minecraft/saves which is default for Linux. Windows is saved in ~/AppData/Roaming/.minecraft/saves

Propose following fix:
![image](https://user-images.githubusercontent.com/40676825/78378164-98f99f00-759e-11ea-88cd-ba6c1e6f16a5.png)

**Comment by ievans3024** [comment]
Use the [`platform`](https://docs.python.org/3.6/library/platform.html) package for more reliable detection.
